services:
  postgresql:
    image: postgres:17
    container_name: cancellation
    environment:
      POSTGRES_PASSWORD: cancellation
      POSTGRES_USER: cancellation
      POSTGRES_DB: cancellation
      TZ: UTC
    ports:
      - "5555:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - web:/code/app
    environment:
      - DATABASE_URL=postgresql://cancellation:cancellation@postgresql:5432/cancellation
      - DEPLOY_MODE="PRODUCTION"
      - MINIMUM_POOL_SIZE=1
      - MAXIMUM_POOL_SIZE=10
    depends_on:
      - postgresql

volumes:
  postgresql:
  web:

